# Generated by Django 5.1.2 on 2024-10-23 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_remove_student_department_alter_student_standard'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeeDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('standard', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10')], max_length=2)),
                ('amount', models.FloatField()),
                ('due_date', models.DateField()),
            ],
        ),
        migrations.AlterField(
            model_name='feeshistory',
            name='status',
            field=models.CharField(blank=True, choices=[('due', 'Due'), ('paid', 'Paid')], max_length=10, null=True),
        ),
    ]
