# Generated by Django 5.1.2 on 2024-10-24 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_feedetails_alter_feeshistory_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='user',
        ),
        migrations.AddField(
            model_name='student',
            name='gender',
            field=models.CharField(choices=[('m', 'Male'), ('f', 'Female')], default=2, max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='mob',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='student',
            name='name',
            field=models.CharField(default=2, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='profile_pic',
            field=models.ImageField(default=2, upload_to='student Picture'),
            preserve_default=False,
        ),
    ]
