# Generated by Django 5.1.2 on 2024-10-24 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_remove_staff_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='department',
            field=models.CharField(choices=[('office', 'Office Staff'), ('librarian', 'Librarian')], max_length=50),
        ),
    ]
