# Generated by Django 5.1.2 on 2024-10-21 14:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('librarian', '0002_alter_libraryrecord_student'),
        ('student', '0003_feeshistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libraryrecord',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.student'),
        ),
    ]
